# Generated by Django 4.2.2 on 2024-02-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='plays',
            field=models.IntegerField(default=0),
        ),
    ]
